### ISSUE TITLE
Validate bit ranges for fields.

### ISSUE THREAD

**Issue by liarokapisv** [diondokter/device-driver#21]
Hi there, thanks for the great crate.
I propose adding validation functionality for the field definitions so that the specified bit-ranges cover exactly all specified register `SIZE_BITS` and so that they do not overlap. Currently, a bit-range can be out of bounds and the macro does not catch it.

**Comment by diondokter** [comment]
Hey thanks!
Ah yes you're right. This is a good thing to add.
(Though overlapping or duplicated fields might be seen as a feature. Though usually if this is required the whole register definition changes)

Now... I'm not sure when I have time to implement this.
If you feel up to it, feel free to give it a shot!

Currently all checking is incorporated into the types, but this needs to be a runtime check.

Probably good to put that check on the Device struct here: https://github.com/diondokter/device-driver/blob/872a04867360c02c4823368af7ca7b683350f313/generation/src/lib.rs#L18
That's the object that acts as the intermediate layer between input and generated code.

Then before the generation functions are called on the device that new check function has to be called.
Only two places for that. Here: https://github.com/diondokter/device-driver/blob/872a04867360c02c4823368af7ca7b683350f313/macros/src/from_file.rs#L103-L108
And here: https://github.com/diondokter/device-driver/blob/872a04867360c02c4823368af7ca7b683350f313/macros/src/from_macro.rs#L425-L429
